"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = require("express");
const InventoryController_1 = require("../controllers/inventory/InventoryController");
const authMiddleware_1 = require("../middlewares/authMiddleware");
const permissionGuard_1 = require("../middlewares/guards/permissionGuard");
const moduleInitializedGuard_1 = require("../middlewares/guards/moduleInitializedGuard");
const router = (0, express_1.Router)();
router.use(authMiddleware_1.authMiddleware);
router.post('/initialize', (0, permissionGuard_1.permissionGuard)('inventory.settings.manage'), InventoryController_1.InventoryController.initialize);
router.get('/settings', (0, permissionGuard_1.permissionGuard)('inventory.view'), InventoryController_1.InventoryController.getSettings);
router.use((0, moduleInitializedGuard_1.moduleInitializedGuard)('inventory'));
router.put('/settings', (0, permissionGuard_1.permissionGuard)('inventory.settings.manage'), InventoryController_1.InventoryController.updateSettings);
router.get('/items/search', (0, permissionGuard_1.permissionGuard)('inventory.items.view'), InventoryController_1.InventoryController.searchItems);
router.post('/items', (0, permissionGuard_1.permissionGuard)('inventory.items.manage'), InventoryController_1.InventoryController.createItem);
router.get('/items', (0, permissionGuard_1.permissionGuard)('inventory.items.view'), InventoryController_1.InventoryController.listItems);
router.get('/items/:id', (0, permissionGuard_1.permissionGuard)('inventory.items.view'), InventoryController_1.InventoryController.getItem);
router.put('/items/:id', (0, permissionGuard_1.permissionGuard)('inventory.items.manage'), InventoryController_1.InventoryController.updateItem);
router.delete('/items/:id', (0, permissionGuard_1.permissionGuard)('inventory.items.manage'), InventoryController_1.InventoryController.deleteItem);
router.post('/categories', (0, permissionGuard_1.permissionGuard)('inventory.categories.manage'), InventoryController_1.InventoryController.createCategory);
router.get('/categories', (0, permissionGuard_1.permissionGuard)('inventory.categories.view'), InventoryController_1.InventoryController.listCategories);
router.put('/categories/:id', (0, permissionGuard_1.permissionGuard)('inventory.categories.manage'), InventoryController_1.InventoryController.updateCategory);
router.delete('/categories/:id', (0, permissionGuard_1.permissionGuard)('inventory.categories.manage'), InventoryController_1.InventoryController.deleteCategory);
router.post('/warehouses', (0, permissionGuard_1.permissionGuard)('inventory.warehouses.manage'), InventoryController_1.InventoryController.createWarehouse);
router.get('/warehouses', (0, permissionGuard_1.permissionGuard)('inventory.warehouses.view'), InventoryController_1.InventoryController.listWarehouses);
router.get('/warehouses/:id', (0, permissionGuard_1.permissionGuard)('inventory.warehouses.view'), InventoryController_1.InventoryController.getWarehouse);
router.put('/warehouses/:id', (0, permissionGuard_1.permissionGuard)('inventory.warehouses.manage'), InventoryController_1.InventoryController.updateWarehouse);
router.post('/uom-conversions', (0, permissionGuard_1.permissionGuard)('inventory.uom.manage'), InventoryController_1.InventoryController.createUomConversion);
router.get('/uom-conversions/:itemId', (0, permissionGuard_1.permissionGuard)('inventory.uom.view'), InventoryController_1.InventoryController.listUomConversions);
router.get('/stock-levels', (0, permissionGuard_1.permissionGuard)('inventory.stock.view'), InventoryController_1.InventoryController.getStockLevels);
router.post('/stock-levels/reserve', (0, permissionGuard_1.permissionGuard)('inventory.stock.adjust'), InventoryController_1.InventoryController.reserveStock);
router.post('/stock-levels/release', (0, permissionGuard_1.permissionGuard)('inventory.stock.adjust'), InventoryController_1.InventoryController.releaseStock);
router.get('/stock-levels/:itemId', (0, permissionGuard_1.permissionGuard)('inventory.stock.view'), InventoryController_1.InventoryController.getStockLevelsByItem);
router.get('/movements', (0, permissionGuard_1.permissionGuard)('inventory.movements.view'), InventoryController_1.InventoryController.getMovements);
router.get('/movements/by-reference', (0, permissionGuard_1.permissionGuard)('inventory.movements.view'), InventoryController_1.InventoryController.getMovementByReference);
router.get('/movements/:itemId', (0, permissionGuard_1.permissionGuard)('inventory.movements.view'), InventoryController_1.InventoryController.getMovementsByItem);
router.post('/movements/opening', (0, permissionGuard_1.permissionGuard)('inventory.movements.record'), InventoryController_1.InventoryController.recordOpeningStock);
router.post('/movements/return', (0, permissionGuard_1.permissionGuard)('inventory.movements.record'), InventoryController_1.InventoryController.processReturn);
router.post('/opening-stock-documents', (0, permissionGuard_1.permissionGuard)('inventory.movements.record'), InventoryController_1.InventoryController.createOpeningStockDocument);
router.get('/opening-stock-documents', (0, permissionGuard_1.permissionGuard)('inventory.movements.record'), InventoryController_1.InventoryController.listOpeningStockDocuments);
router.put('/opening-stock-documents/:id', (0, permissionGuard_1.permissionGuard)('inventory.movements.record'), InventoryController_1.InventoryController.updateOpeningStockDocument);
router.delete('/opening-stock-documents/:id', (0, permissionGuard_1.permissionGuard)('inventory.movements.record'), InventoryController_1.InventoryController.deleteOpeningStockDocument);
router.post('/opening-stock-documents/:id/post', (0, permissionGuard_1.permissionGuard)('inventory.movements.record'), InventoryController_1.InventoryController.postOpeningStockDocument);
router.post('/adjustments', (0, permissionGuard_1.permissionGuard)('inventory.stock.adjust'), InventoryController_1.InventoryController.createAdjustment);
router.get('/adjustments', (0, permissionGuard_1.permissionGuard)('inventory.stock.adjust'), InventoryController_1.InventoryController.listAdjustments);
router.post('/adjustments/:id/post', (0, permissionGuard_1.permissionGuard)('inventory.stock.adjust'), InventoryController_1.InventoryController.postAdjustment);
router.post('/transfers', (0, permissionGuard_1.permissionGuard)('inventory.stock.adjust'), InventoryController_1.InventoryController.createTransfer);
router.post('/transfers/:id/complete', (0, permissionGuard_1.permissionGuard)('inventory.stock.adjust'), InventoryController_1.InventoryController.completeTransfer);
router.get('/transfers', (0, permissionGuard_1.permissionGuard)('inventory.stock.view'), InventoryController_1.InventoryController.listTransfers);
router.post('/snapshots', (0, permissionGuard_1.permissionGuard)('inventory.valuation.view'), InventoryController_1.InventoryController.createSnapshot);
router.get('/valuation/as-of', (0, permissionGuard_1.permissionGuard)('inventory.valuation.view'), InventoryController_1.InventoryController.getAsOfValuation);
router.get('/valuation', (0, permissionGuard_1.permissionGuard)('inventory.valuation.view'), InventoryController_1.InventoryController.getValuation);
router.get('/costs/current', (0, permissionGuard_1.permissionGuard)('inventory.stock.view'), InventoryController_1.InventoryController.getCurrentCost);
router.get('/dashboard', (0, permissionGuard_1.permissionGuard)('inventory.view'), InventoryController_1.InventoryController.getDashboard);
router.get('/alerts/low-stock', (0, permissionGuard_1.permissionGuard)('inventory.stock.view'), InventoryController_1.InventoryController.getLowStockAlerts);
router.get('/reports/unsettled-costs', (0, permissionGuard_1.permissionGuard)('inventory.movements.view'), InventoryController_1.InventoryController.getUnsettledCosts);
router.post('/reconcile', (0, permissionGuard_1.permissionGuard)('inventory.reconcile.run'), InventoryController_1.InventoryController.reconcile);
exports.default = router;
//# sourceMappingURL=inventory.routes.js.map