"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = require("express");
const PurchaseController_1 = require("../controllers/purchases/PurchaseController");
const authMiddleware_1 = require("../middlewares/authMiddleware");
const moduleInitializedGuard_1 = require("../middlewares/guards/moduleInitializedGuard");
const router = (0, express_1.Router)();
router.use(authMiddleware_1.authMiddleware);
router.post('/initialize', PurchaseController_1.PurchaseController.initializePurchases);
router.get('/settings', PurchaseController_1.PurchaseController.getSettings);
router.use((0, moduleInitializedGuard_1.moduleInitializedGuard)('purchase'));
router.put('/settings', PurchaseController_1.PurchaseController.updateSettings);
router.post('/orders', PurchaseController_1.PurchaseController.createPO);
router.get('/orders', PurchaseController_1.PurchaseController.listPOs);
router.get('/orders/:id', PurchaseController_1.PurchaseController.getPO);
router.put('/orders/:id', PurchaseController_1.PurchaseController.updatePO);
router.post('/orders/:id/confirm', PurchaseController_1.PurchaseController.confirmPO);
router.post('/orders/:id/cancel', PurchaseController_1.PurchaseController.cancelPO);
router.post('/orders/:id/close', PurchaseController_1.PurchaseController.closePO);
router.post('/goods-receipts', PurchaseController_1.PurchaseController.createGRN);
router.get('/goods-receipts', PurchaseController_1.PurchaseController.listGRNs);
router.get('/goods-receipts/:id', PurchaseController_1.PurchaseController.getGRN);
router.put('/goods-receipts/:id', PurchaseController_1.PurchaseController.updateGRN);
router.post('/goods-receipts/:id/post', PurchaseController_1.PurchaseController.postGRN);
router.post('/goods-receipts/:id/unpost', PurchaseController_1.PurchaseController.unpostGRN);
router.post('/invoices', PurchaseController_1.PurchaseController.createPI);
router.get('/invoices', PurchaseController_1.PurchaseController.listPIs);
router.get('/invoices/:id', PurchaseController_1.PurchaseController.getPI);
router.put('/invoices/:id', PurchaseController_1.PurchaseController.updatePI);
router.post('/invoices/:id/post', PurchaseController_1.PurchaseController.postPI);
router.post('/invoices/:id/unpost', PurchaseController_1.PurchaseController.unpostPI);
router.post('/invoices/:id/payment-update', PurchaseController_1.PurchaseController.updatePaymentStatus);
router.post('/returns', PurchaseController_1.PurchaseController.createReturn);
router.get('/returns', PurchaseController_1.PurchaseController.listReturns);
router.get('/returns/:id', PurchaseController_1.PurchaseController.getReturn);
router.put('/returns/:id', PurchaseController_1.PurchaseController.updateReturn);
router.post('/returns/:id/post', PurchaseController_1.PurchaseController.postReturn);
router.post('/returns/:id/unpost', PurchaseController_1.PurchaseController.unpostReturn);
exports.default = router;
//# sourceMappingURL=purchases.routes.js.map