"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = require("express");
const SalesController_1 = require("../controllers/sales/SalesController");
const authMiddleware_1 = require("../middlewares/authMiddleware");
const moduleInitializedGuard_1 = require("../middlewares/guards/moduleInitializedGuard");
const router = (0, express_1.Router)();
router.use(authMiddleware_1.authMiddleware);
router.post('/initialize', SalesController_1.SalesController.initializeSales);
router.get('/settings', SalesController_1.SalesController.getSettings);
router.use((0, moduleInitializedGuard_1.moduleInitializedGuard)('sales'));
router.put('/settings', SalesController_1.SalesController.updateSettings);
router.post('/orders', SalesController_1.SalesController.createSO);
router.get('/orders', SalesController_1.SalesController.listSOs);
router.get('/orders/:id', SalesController_1.SalesController.getSO);
router.put('/orders/:id', SalesController_1.SalesController.updateSO);
router.post('/orders/:id/confirm', SalesController_1.SalesController.confirmSO);
router.post('/orders/:id/cancel', SalesController_1.SalesController.cancelSO);
router.post('/orders/:id/close', SalesController_1.SalesController.closeSO);
router.post('/delivery-notes', SalesController_1.SalesController.createDN);
router.get('/delivery-notes', SalesController_1.SalesController.listDNs);
router.get('/delivery-notes/:id', SalesController_1.SalesController.getDN);
router.post('/delivery-notes/:id/post', SalesController_1.SalesController.postDN);
router.post('/invoices', SalesController_1.SalesController.createSI);
router.get('/invoices', SalesController_1.SalesController.listSIs);
router.get('/invoices/:id', SalesController_1.SalesController.getSI);
router.put('/invoices/:id', SalesController_1.SalesController.updateSI);
router.post('/invoices/:id/post', SalesController_1.SalesController.postSI);
router.post('/invoices/:id/payment-status', SalesController_1.SalesController.updatePaymentStatus);
router.post('/returns', SalesController_1.SalesController.createReturn);
router.get('/returns', SalesController_1.SalesController.listReturns);
router.get('/returns/:id', SalesController_1.SalesController.getReturn);
router.post('/returns/:id/post', SalesController_1.SalesController.postReturn);
exports.default = router;
//# sourceMappingURL=sales.routes.js.map